runtime: php
env: flex

env_variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: csi3540
    POSTGRES_DSN: pgsql:dbname=wbprojdb;host=/cloudsql/wbproj-csi3540:us-central1:wbprojdb

runtime_config:
  document_root: web

## Uncomment for Cloud SQL
beta_settings:
   cloud_sql_instances: "wbproj-csi3540:us-central1:wbprojdb"

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10